"""Render a brief's structured content into a 1-page PDF.

- Free tier: watermarked ("ANTEROOM FREE" diagonal, faint ribbon)
- Pro tier: clean

Uses reportlab so the whole PDF is server-generated bytes, no browsers needed.
"""

from __future__ import annotations

import io
from typing import Any, Optional

import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


BRAND = colors.HexColor("#365F50")
INK = colors.HexColor("#111815")
MUTED = colors.HexColor("#698075")
LINE = colors.HexColor("#E6EDE9")
ACCENT = colors.HexColor("#4B7A68")


def _draw_multiline(
    c: canvas.Canvas,
    text: str,
    x: float,
    y: float,
    max_width: float,
    font: str,
    size: float,
    leading: Optional[float] = None,
    color=INK,
) -> float:
    """Wrap `text` at `max_width` and return the new baseline y."""
    c.setFont(font, size)
    c.setFillColor(color)
    leading = leading or size + 2
    words = text.split()
    line = ""
    for w in words:
        candidate = f"{line} {w}".strip()
        if c.stringWidth(candidate, font, size) <= max_width:
            line = candidate
        else:
            if line:
                c.drawString(x, y, line)
                y -= leading
            line = w
    if line:
        c.drawString(x, y, line)
        y -= leading
    return y


def _draw_watermark(c: canvas.Canvas, page_w: float, page_h: float) -> None:
    """Diagonal faint 'ANTEROOM FREE' across the page, plus a top ribbon."""
    c.saveState()
    c.setFillColor(colors.Color(0.55, 0.63, 0.58, alpha=0.15))
    c.setFont("Helvetica-Bold", 90)
    c.translate(page_w / 2, page_h / 2)
    c.rotate(30)
    c.drawCentredString(0, 0, "ANTEROOM FREE")
    c.restoreState()

    # Top-right ribbon
    c.saveState()
    c.setFillColor(colors.Color(0.21, 0.37, 0.31, alpha=0.9))
    c.rect(page_w - 42 * mm, page_h - 10 * mm, 42 * mm, 6 * mm, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(page_w - 21 * mm, page_h - 8 * mm, "ANTEROOM FREE — Upgrade for clean export")
    c.restoreState()


def _generate_qr_png(url: str) -> bytes:
    img = qrcode.make(url, box_size=6, border=2)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def render_brief_pdf(
    content: dict,
    *,
    doc_type_label: str = "Pre-visit brief",
    generated_at: str = "",
    watermarked: bool = True,
    share_url: Optional[str] = None,
    brief_id: str = "",
) -> bytes:
    """Render a single-page A4 PDF from a sanitized brief content dict."""
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    page_w, page_h = A4
    margin_x = 20 * mm
    right_x = page_w - margin_x
    y = page_h - 20 * mm

    # Header
    c.setFillColor(BRAND)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(margin_x, y, "Anteroom")
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 9)
    c.drawString(margin_x, y - 12, "Pre-visit brief")
    if generated_at:
        c.drawRightString(right_x, y, f"Generated {generated_at}")
    c.setFillColor(LINE)
    c.setLineWidth(0.5)
    c.line(margin_x, y - 18, right_x, y - 18)
    y -= 30

    patient = content.get("patient") or {}
    referral = content.get("referral_reason")
    meds = content.get("medications") or []
    allergies = content.get("allergies") or []
    flagged = content.get("flagged_items") or []

    # Patient block
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, "Patient")
    y -= 14
    c.setFont("Helvetica", 10)
    patient_lines = []
    if patient.get("name"):
        patient_lines.append(("Name", patient["name"]))
    if patient.get("dob"):
        patient_lines.append(("DOB", patient["dob"]))
    if patient.get("sex"):
        patient_lines.append(("Sex", patient["sex"]))
    if patient.get("id_number"):
        patient_lines.append(("ID", patient["id_number"]))
    if not patient_lines:
        c.setFillColor(MUTED)
        c.drawString(margin_x, y, "No patient details detected on the pages.")
        y -= 14
        c.setFillColor(INK)
    else:
        for label, value in patient_lines:
            c.setFillColor(MUTED)
            c.drawString(margin_x, y, f"{label}")
            c.setFillColor(INK)
            c.drawString(margin_x + 25 * mm, y, str(value))
            y -= 12
    y -= 6

    # Referral reason
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, "Referral reason")
    y -= 14
    if referral:
        y = _draw_multiline(
            c, referral, margin_x, y, right_x - margin_x - 55 * mm,
            "Helvetica", 10, leading=13,
        )
    else:
        c.setFillColor(MUTED)
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(margin_x, y, "Not detected on the pages.")
        y -= 12
    y -= 8

    # Medications
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, f"Medications ({len(meds)})")
    y -= 14
    if meds:
        col2 = margin_x + 65 * mm
        col3 = margin_x + 115 * mm
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(MUTED)
        c.drawString(margin_x, y, "NAME")
        c.drawString(col2, y, "DOSE")
        c.drawString(col3, y, "FREQUENCY")
        y -= 12
        c.setFont("Helvetica", 10)
        c.setFillColor(INK)
        for m in meds[:12]:
            if y < 90 * mm:
                break  # stay 1-page
            c.drawString(margin_x, y, (m.get("name") or "")[:38])
            c.drawString(col2, y, (m.get("dose") or "—")[:22])
            c.drawString(col3, y, (m.get("frequency") or "—")[:36])
            y -= 12
    else:
        c.setFillColor(MUTED)
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(margin_x, y, "None detected.")
        y -= 12
    y -= 6

    # Allergies
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, f"Allergies ({len(allergies)})")
    y -= 14
    if allergies:
        c.setFont("Helvetica", 10)
        c.setFillColor(INK)
        for a in allergies[:8]:
            if y < 65 * mm:
                break
            substance = a.get("substance") or ""
            reaction = a.get("reaction")
            line = substance + (f" — {reaction}" if reaction else "")
            y = _draw_multiline(
                c, line, margin_x, y, right_x - margin_x - 55 * mm,
                "Helvetica", 10, leading=13,
            )
    else:
        c.setFillColor(MUTED)
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(margin_x, y, "None detected.")
        y -= 12
    y -= 6

    # Flagged for review
    if flagged:
        c.setFillColor(colors.HexColor("#9E3838"))
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin_x, y, "Flagged for review")
        y -= 14
        c.setFillColor(INK)
        c.setFont("Helvetica", 10)
        for f in flagged[:6]:
            if y < 55 * mm:
                break
            y = _draw_multiline(
                c, f"• {f}", margin_x, y, right_x - margin_x - 55 * mm,
                "Helvetica", 10, leading=13,
            )

    # QR code — bottom right
    if share_url:
        try:
            qr_png = _generate_qr_png(share_url)
            from reportlab.lib.utils import ImageReader
            qr_img = ImageReader(io.BytesIO(qr_png))
            qr_size = 34 * mm
            qr_x = right_x - qr_size
            qr_y = 20 * mm
            c.drawImage(qr_img, qr_x, qr_y, qr_size, qr_size)
            c.setFillColor(MUTED)
            c.setFont("Helvetica", 7)
            c.drawRightString(right_x, qr_y - 4, "Scan to view online")
        except Exception:
            pass

    # Footer
    c.setFillColor(LINE)
    c.line(margin_x, 15 * mm, right_x, 15 * mm)
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 8)
    c.drawString(margin_x, 10 * mm, f"Anteroom pre-visit brief • ID {brief_id}")
    c.drawRightString(right_x, 10 * mm, "Extracted directly from patient documents — no diagnosis.")

    if watermarked:
        _draw_watermark(c, page_w, page_h)

    c.showPage()
    c.save()
    return buf.getvalue()
