"""Render a brief's structured content into a 1-page PDF.

- Free tier: watermarked ("ANTEROOM FREE" diagonal, faint ribbon)
- Pro tier: clean

Uses reportlab so the whole PDF is server-generated bytes, no browsers needed.
"""

from __future__ import annotations

import io
from typing import Any, Optional

import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


BRAND = colors.HexColor("#365F50")
INK = colors.HexColor("#111815")
MUTED = colors.HexColor("#698075")
LINE = colors.HexColor("#E6EDE9")
ACCENT = colors.HexColor("#4B7A68")


LABELS = {
    "en": {
        "subtitle": "Pre-visit brief",
        "generated": "Generated",
        "patient": "Patient",
        "name": "Name",
        "dob": "DOB",
        "sex": "Sex",
        "id": "ID",
        "no_patient": "No patient details detected on the pages.",
        "referral": "Referral reason",
        "not_detected": "Not detected on the pages.",
        "medications": "Medications",
        "col_name": "NAME",
        "col_dose": "DOSE",
        "col_freq": "FREQUENCY",
        "none": "None detected.",
        "allergies": "Allergies",
        "flagged": "Flagged for review",
        "scan": "Scan to view online",
        "footer_id": "Anteroom pre-visit brief • ID",
        "footer_note": "From the patient's own documents. Not a medical device — no diagnosis. Check against the originals.",
        "watermark_ribbon": "ANTEROOM FREE — Upgrade for clean export",
    },
    "es": {
        "subtitle": "Resumen previo a la visita",
        "generated": "Generado",
        "patient": "Paciente",
        "name": "Nombre",
        "dob": "Fecha nac.",
        "sex": "Sexo",
        "id": "ID",
        "no_patient": "No se detectaron datos del paciente en las páginas.",
        "referral": "Motivo de derivación",
        "not_detected": "No detectado en las páginas.",
        "medications": "Medicamentos",
        "col_name": "NOMBRE",
        "col_dose": "DOSIS",
        "col_freq": "FRECUENCIA",
        "none": "No se detectaron.",
        "allergies": "Alergias",
        "flagged": "Marcado para revisar",
        "scan": "Escanear para ver en línea",
        "footer_id": "Resumen previo Anteroom • ID",
        "footer_note": "De los documentos del propio paciente. No es un producto sanitario — sin diagnóstico. Compruebe con los originales.",
        "watermark_ribbon": "ANTEROOM FREE — Actualiza para exportar sin marca",
    },
}


def _draw_multiline(
    c: canvas.Canvas,
    text: str,
    x: float,
    y: float,
    max_width: float,
    font: str,
    size: float,
    leading: Optional[float] = None,
    color=INK,
) -> float:
    """Wrap `text` at `max_width` and return the new baseline y."""
    c.setFont(font, size)
    c.setFillColor(color)
    leading = leading or size + 2
    words = text.split()
    line = ""
    for w in words:
        candidate = f"{line} {w}".strip()
        if c.stringWidth(candidate, font, size) <= max_width:
            line = candidate
        else:
            if line:
                c.drawString(x, y, line)
                y -= leading
            line = w
    if line:
        c.drawString(x, y, line)
        y -= leading
    return y


def _draw_watermark(c: canvas.Canvas, page_w: float, page_h: float, ribbon_text: str) -> None:
    """Diagonal faint 'ANTEROOM FREE' across the page, plus a top ribbon."""
    c.saveState()
    c.setFillColor(colors.Color(0.55, 0.63, 0.58, alpha=0.15))
    c.setFont("Helvetica-Bold", 90)
    c.translate(page_w / 2, page_h / 2)
    c.rotate(30)
    c.drawCentredString(0, 0, "ANTEROOM FREE")
    c.restoreState()

    # Top-right ribbon
    c.saveState()
    c.setFillColor(colors.Color(0.21, 0.37, 0.31, alpha=0.9))
    c.rect(page_w - 62 * mm, page_h - 10 * mm, 62 * mm, 6 * mm, stroke=0, fill=1)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 8)
    c.drawCentredString(page_w - 31 * mm, page_h - 8 * mm, ribbon_text)
    c.restoreState()


def _generate_qr_png(url: str) -> bytes:
    img = qrcode.make(url, box_size=6, border=2)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def render_brief_pdf(
    content: dict,
    *,
    doc_type_label: str = "Pre-visit brief",
    generated_at: str = "",
    watermarked: bool = True,
    share_url: Optional[str] = None,
    brief_id: str = "",
    language: str = "en",
) -> bytes:
    """Render a single-page A4 PDF from a sanitized brief content dict."""
    L = LABELS.get(language, LABELS["en"])
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    page_w, page_h = A4
    margin_x = 20 * mm
    right_x = page_w - margin_x
    y = page_h - 20 * mm

    # Header
    c.setFillColor(BRAND)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(margin_x, y, "Anteroom")
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 9)
    c.drawString(margin_x, y - 12, L["subtitle"])
    if generated_at:
        c.drawRightString(right_x, y, f"{L['generated']} {generated_at}")
    c.setFillColor(LINE)
    c.setLineWidth(0.5)
    c.line(margin_x, y - 18, right_x, y - 18)
    y -= 30

    patient = content.get("patient") or {}
    referral = content.get("referral_reason")
    meds = content.get("medications") or []
    allergies = content.get("allergies") or []
    flagged = content.get("flagged_items") or []

    # Patient block
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, L["patient"])
    y -= 14
    c.setFont("Helvetica", 10)
    patient_lines = []
    if patient.get("name"):
        patient_lines.append((L["name"], patient["name"]))
    if patient.get("dob"):
        patient_lines.append((L["dob"], patient["dob"]))
    if patient.get("sex"):
        patient_lines.append((L["sex"], patient["sex"]))
    if patient.get("id_number"):
        patient_lines.append((L["id"], patient["id_number"]))
    if not patient_lines:
        c.setFillColor(MUTED)
        c.drawString(margin_x, y, L["no_patient"])
        y -= 14
        c.setFillColor(INK)
    else:
        for label, value in patient_lines:
            c.setFillColor(MUTED)
            c.drawString(margin_x, y, f"{label}")
            c.setFillColor(INK)
            c.drawString(margin_x + 30 * mm, y, str(value))
            y -= 12
    y -= 6

    # Referral reason
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, L["referral"])
    y -= 14
    if referral:
        y = _draw_multiline(
            c, referral, margin_x, y, right_x - margin_x - 55 * mm,
            "Helvetica", 10, leading=13,
        )
    else:
        c.setFillColor(MUTED)
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(margin_x, y, L["not_detected"])
        y -= 12
    y -= 8

    # Medications
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, f"{L['medications']} ({len(meds)})")
    y -= 14
    if meds:
        col2 = margin_x + 65 * mm
        col3 = margin_x + 115 * mm
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(MUTED)
        c.drawString(margin_x, y, L["col_name"])
        c.drawString(col2, y, L["col_dose"])
        c.drawString(col3, y, L["col_freq"])
        y -= 12
        c.setFont("Helvetica", 10)
        c.setFillColor(INK)
        for m in meds[:12]:
            if y < 90 * mm:
                break  # stay 1-page
            c.drawString(margin_x, y, (m.get("name") or "")[:38])
            c.drawString(col2, y, (m.get("dose") or "—")[:22])
            c.drawString(col3, y, (m.get("frequency") or "—")[:36])
            y -= 12
    else:
        c.setFillColor(MUTED)
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(margin_x, y, L["none"])
        y -= 12
    y -= 6

    # Allergies
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(margin_x, y, f"{L['allergies']} ({len(allergies)})")
    y -= 14
    if allergies:
        c.setFont("Helvetica", 10)
        c.setFillColor(INK)
        for a in allergies[:8]:
            if y < 65 * mm:
                break
            substance = a.get("substance") or ""
            reaction = a.get("reaction")
            line = substance + (f" — {reaction}" if reaction else "")
            y = _draw_multiline(
                c, line, margin_x, y, right_x - margin_x - 55 * mm,
                "Helvetica", 10, leading=13,
            )
    else:
        c.setFillColor(MUTED)
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(margin_x, y, L["none"])
        y -= 12
    y -= 6

    # Flagged for review
    if flagged:
        c.setFillColor(colors.HexColor("#9E3838"))
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin_x, y, L["flagged"])
        y -= 14
        c.setFillColor(INK)
        c.setFont("Helvetica", 10)
        for f in flagged[:6]:
            if y < 55 * mm:
                break
            y = _draw_multiline(
                c, f"• {f}", margin_x, y, right_x - margin_x - 55 * mm,
                "Helvetica", 10, leading=13,
            )

    # QR code — bottom right
    if share_url:
        try:
            qr_png = _generate_qr_png(share_url)
            from reportlab.lib.utils import ImageReader
            qr_img = ImageReader(io.BytesIO(qr_png))
            qr_size = 34 * mm
            qr_x = right_x - qr_size
            qr_y = 20 * mm
            c.drawImage(qr_img, qr_x, qr_y, qr_size, qr_size)
            c.setFillColor(MUTED)
            c.setFont("Helvetica", 7)
            c.drawRightString(right_x, qr_y - 4, L["scan"])
        except Exception:
            pass

    # Footer
    c.setFillColor(LINE)
    c.line(margin_x, 15 * mm, right_x, 15 * mm)
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 8)
    c.drawString(margin_x, 10 * mm, f"{L['footer_id']} {brief_id}")
    c.drawRightString(right_x, 10 * mm, L["footer_note"])

    if watermarked:
        _draw_watermark(c, page_w, page_h, L["watermark_ribbon"])

    c.showPage()
    c.save()
    return buf.getvalue()
